// Package jellygen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package jellygen

// Defines values for BaseItemKind.
const (
	BaseItemKindAggregateFolder       BaseItemKind = "AggregateFolder"
	BaseItemKindAudio                 BaseItemKind = "Audio"
	BaseItemKindAudioBook             BaseItemKind = "AudioBook"
	BaseItemKindBasePluginFolder      BaseItemKind = "BasePluginFolder"
	BaseItemKindBook                  BaseItemKind = "Book"
	BaseItemKindBoxSet                BaseItemKind = "BoxSet"
	BaseItemKindChannel               BaseItemKind = "Channel"
	BaseItemKindChannelFolderItem     BaseItemKind = "ChannelFolderItem"
	BaseItemKindCollectionFolder      BaseItemKind = "CollectionFolder"
	BaseItemKindEpisode               BaseItemKind = "Episode"
	BaseItemKindFolder                BaseItemKind = "Folder"
	BaseItemKindGenre                 BaseItemKind = "Genre"
	BaseItemKindLiveTvChannel         BaseItemKind = "LiveTvChannel"
	BaseItemKindLiveTvProgram         BaseItemKind = "LiveTvProgram"
	BaseItemKindManualPlaylistsFolder BaseItemKind = "ManualPlaylistsFolder"
	BaseItemKindMovie                 BaseItemKind = "Movie"
	BaseItemKindMusicAlbum            BaseItemKind = "MusicAlbum"
	BaseItemKindMusicArtist           BaseItemKind = "MusicArtist"
	BaseItemKindMusicGenre            BaseItemKind = "MusicGenre"
	BaseItemKindMusicVideo            BaseItemKind = "MusicVideo"
	BaseItemKindPerson                BaseItemKind = "Person"
	BaseItemKindPhoto                 BaseItemKind = "Photo"
	BaseItemKindPhotoAlbum            BaseItemKind = "PhotoAlbum"
	BaseItemKindPlaylist              BaseItemKind = "Playlist"
	BaseItemKindPlaylistsFolder       BaseItemKind = "PlaylistsFolder"
	BaseItemKindProgram               BaseItemKind = "Program"
	BaseItemKindRecording             BaseItemKind = "Recording"
	BaseItemKindSeason                BaseItemKind = "Season"
	BaseItemKindSeries                BaseItemKind = "Series"
	BaseItemKindStudio                BaseItemKind = "Studio"
	BaseItemKindTrailer               BaseItemKind = "Trailer"
	BaseItemKindTvChannel             BaseItemKind = "TvChannel"
	BaseItemKindTvProgram             BaseItemKind = "TvProgram"
	BaseItemKindUserRootFolder        BaseItemKind = "UserRootFolder"
	BaseItemKindUserView              BaseItemKind = "UserView"
	BaseItemKindVideo                 BaseItemKind = "Video"
	BaseItemKindYear                  BaseItemKind = "Year"
)

// BaseItemDto This is strictly used as a data transfer object from the api layer.
// This holds information about a BaseItem in a format that is convenient for the client.
type BaseItemDto struct {
	// Id Gets or sets the id.
	Id *string `json:"Id,omitempty"`

	// IndexNumber Gets or sets the index number.
	IndexNumber *int32 `json:"IndexNumber"`

	// Name Gets or sets the name.
	Name          *string `json:"Name"`
	OriginalTitle *string `json:"OriginalTitle"`

	// ParentIndexNumber Gets or sets the parent index number.
	ParentIndexNumber *int32 `json:"ParentIndexNumber"`

	// Path Gets or sets the path.
	Path *string `json:"Path"`

	// ProviderIds Gets or sets the provider ids.
	ProviderIds *map[string]string `json:"ProviderIds,omitempty,omitzero"`

	// Type Gets or sets the type.
	Type *BaseItemKind `json:"Type,omitempty"`

	// UserData Gets or sets the user data for this item based on the user it's being requested for.
	UserData *UserItemDataDto `json:"UserData"`
}

// BaseItemKind The base item kind.
type BaseItemKind string

// UserItemDataDto Class UserItemDataDto.
type UserItemDataDto struct {
	// IsFavorite Gets or sets a value indicating whether this instance is favorite.
	IsFavorite *bool `json:"IsFavorite,omitempty"`
}
